language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

branches:
  except:
    - /^(release\/|hotfix\/)?\d\.\d/

install:
  - composer install

script: ./vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text
